version: "3.8"
services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  givefreely:
    container_name: givefreelyapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api-network
    ports:
      - "5000:5000"
volumes:
  db:
    driver: local
networks:
  api-network:
    driver: bridge
